### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by msmanui** [PyvesB/advanced-achievements#1030]
Hi there.

I would like to see the configuration of the gui. This is to check how customizable the gui is. I've used the free version in the past and it wasnt at my expectations. Therefore, if the gui is customizable (Like DeluxeMenu) i would buy the plugins.

Thanks.

**Comment by PyvesB** [comment]
@msmanui and their other @asdasasf1 account have created a total of 10 issues, some of which needed to be deleted from this repository due to abusive behaviour towards some members of the community. Once again, this new issue is a duplicate, makes little sense and does not follow the issue template. Repeatedly creating poor quality issues is contrary to the project's goal of providing a harassment-free experience for everyone. In line with the project's [code of conduct](https://github.com/PyvesB/advanced-achievements/blob/master/CODE_OF_CONDUCT.md), I am proceeding to the exclusion of this member and reporting them to GitHub.
