### ISSUE TITLE
Add Boss plugin to advanceachievements request

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#623]
Hello, I was wonder if you're interested in a commission to add the [boss](https://www.spigotmc.org/resources/%E2%98%9B-boss%E2%84%A2-custom-monsters-and-animals-on-your-server-1-8-9-1-14-4-advent-sale.46497/) plugin to your advanceachievements plugin.

I made a ticket in github for this but you rejected it already so I'm curious if you'll do it if I paid you. Also, I tried dming you on spigot but you have them blocked 
Thanks,
  Ergenta

**Comment by ShayPunter** [comment]
Hello!

Just adding onto this, I am currently a developer working on behalf of Ergenta. 

Provided that it is feasible, and we are granted permissions from the author of Boss(TM), and we make some arrangements to see if he will separate the API into a package that we can use for this, would we have permission to implement support for the Boss(TM) plugin into advanced achievements?

All the best,
Shay Punter.

**Comment by PyvesB** [comment]
Hi @ShayPunter,

> would we have permission to implement support for the Boss(TM) plugin into advanced achievements?

Yes, sure, provided you follow the terms of the license. The project is licensed under [GPLv3.0](https://github.com/PyvesB/AdvancedAchievements/blob/master/LICENSE). In particular this means that any changes to add Boss support must be publicly made available under a GPLv3.0-compatible license. The simplest way to achieve this is to simply submit a PR to this repository. 😉

**Comment by ShayPunter** [comment]
Hello @PyvesB,

Thanks for the go-ahead! Just need to check with you now, the API for Boss(TM) is packaged into a jar file, with no code made actually available via his [GitHub page (see release area)](https://github.com/kangarko/Boss), not sure how you would deal with having jar files for dependencies. Ideally, I am going to try and get him to host the API code in a repository that we can add in the pom file, though if that fails, then I more than likely won't implement it, due to the nature of it being in a jar file (which is a pain to manage), instead of a repository and I will have to make the implementation of it exclusively for Ergenta until new options appear.

And I just have to clear up with him what the code is licensed under by since he doesn't state that anywhere, provided everything goes smoothly, should see support for it soon. :)

All the best
Shay Punter

**Comment by PyvesB** [comment]
We could make Maven use the _.jar_ directly, but it's somewhat messy and makes things harder to manage. Ideally the Boss author should publish the API to a Maven repository, this can be done on GitHub directly for example.

**Comment by BobbyMere** [comment]
Would you be able to add this function? Boss has made their API publicly available [here](https://github.com/kangarko/Boss/wiki/Developer-API)

**Comment by PyvesB** [comment]
@ShayPunter is this still on your radar? :)

**Comment by BobbyMere** [comment]
I'm fairly certain he has moved on

**Comment by BobbyMere** [comment]
Any further thoughts?

**Comment by PyvesB** [comment]
There's still a week of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) left, I'll probably close this issue afterwards if no one is able to pick it up.
