### ISSUE TITLE
[Feature Request] Server specific Achievements

### ISSUE THREAD

**Issue by Maliam** [PyvesB/advanced-achievements#739]
Good Morning all,

I've been going through the plugin for a while now and I'm going to start out by saying it's done in an amazingly comprehensive way. This is a GREAT plugin and I want to thank you for all the time you've put into it.

With that being said there is one thing that I know will greatly help out. Server-specific achievement options (for us bungee people). Now In my head this works pretty easily, add a option in the config called "server-name" per achievement (with a GLOBAL option or just a server name option) Default all achievements to global but allow the user to swap it to a specific name. IF the user does swap it to a specific name, have the plugin check it against the server name in server.properties. IF the name matches, award the achievement.

This would allow for specific achievements to be awarded per server. i.e. "Kill 100 people in factions" and "Kill 100 people in skywars" could be separate achievements, adding depth and a desire to try the different game types on servers.

Thank you so much for your time,
~Mal

**Comment by PyvesB** [comment]
Hello @Maliam 

> I've been going through the plugin for a while now and I'm going to start out by saying it's done in an amazingly comprehensive way. This is a GREAT plugin and I want to thank you for all the time you've put into it.

Thanks for the kind words! 👍 

> With that being said there is one thing that I know will greatly help out. Server-specific achievement options (for us bungee people). Now In my head this works pretty easily, add a option in the config called "server-name" per achievement (with a GLOBAL option or just a server name option) Default all achievements to global but allow the user to swap it to a specific name. IF the user does swap it to a specific name, have the plugin check it against the server name in server.properties. IF the name matches, award the achievement.
> 
> This would allow for specific achievements to be awarded per server. i.e. "Kill 100 people in factions" and "Kill 100 people in skywars" could be separate achievements, adding depth and a desire to try the different game types on servers.

Seems like a reasonable idea! I probably won't have time to look into this myself in the coming weeks, however, if someone wants to contribute and pick this one up, I will be glad to review and integrate the pull request into the code base. 😉

**Comment by fjeddy** [comment]
+1, would love to see this implemented.

**Comment by PyvesB** [comment]
I've given this some more thought and analysis. Unfortunately, there would be a lot of challenges around such a feature.

To be able to award achievements such as "Kill 100 people in factions" or "Kill 100 people in skywars", checking against the server name in _server.properties_ at the point of awarding the achievement is not enough. Indeed, you need to know that the 100 kills were done on the specific server, in other words you have to make sure that every statistic is coupled with the server name information.

Technically, this means that all the plugin's database table schemas must be migrated to include a new `server` column. This leads to many problems:
* migrating dozens and dozens of tables potentially containing vast amounts of data is unpractical, it will take significant time on servers and increase the risk of data loss or corruption at the point of migration.
* what should be the server value for existing tables? There's no good answer to that one, if you select one server name randomly or the server performing the migration, players that never play on that server will get confused as their statistics will be far from reality.
* database sizes will increase significantly as a result of this given that they now have an added column of unbounded strings.
* all database queries become more complex: extract fields to write, extra filters when reading statistics for a particular server, queries that sum multiple rows when wanting "global" statistics. This will degrade the performance of database operations.
* the rest of the plugin's code also becomes significantly more complex in places, in particular the caching layers pretty much needs rewriting to deal with this new dimension in statistics. There will also be a performance hit and increased memory usage in the plugin.

Ultimately, I don't think this feature would be used by many people: the plugin has existed for over half a decade and only the two users here have ever asked for this as far as I can remember. All other users will be affected negatively because of increased configuration complexity, increased CPU, memory and disk space usage, and simply because my time/the time of other contributors will be spent on this huge piece of work and ongoing maintenance instead of working on any other features.

Hopefully the detailed explanation makes sense. For now, I'm going to close the issue.
