### ISSUE TITLE
Feature: Time played until achievement is completed...

### ISSUE THREAD

**Issue by fjeddy** [PyvesB/advanced-achievements#756]
Hello,

I know this might possibly be a lot of work to implement, but a feature I would love to see added is a "Game time spent before completion."

Basically, a piece of information attached to each individual achievement saying how long they had played on the server when the achievement was done.

"You earned the achievment "Fish 100 fish", it took you 23 hours and 11 minutes to complete it."

It's not only a fun piece of information, but it would also allow server owners to really see what achievements are taken quickly, and which ones are taking the players longer. Knowing what might be way to easy, or what might be way to difficult.

**Comment by PyvesB** [comment]
Hello @fjeddy,

Given that the plugin already keeps track of each player's total played time and also the achievement reception times, it should be quite easy to get an approximate time played until an achievement is completed. I insist on approximate as time is only updated at regular intervals as defined by the _PlaytimeTaskInterval_ configuration parameter, so it would probably be better to display something like 1.4 hours rather than a more precise count with minutes. The more tricky bit is where to display that information: in _/aach book_, _/aach list_, in the chat, elsewhere?

**Comment by PyvesB** [comment]
There has not been any response to my above question nor any thoughts regarding the approximate nature of the time data. I'm going to assume that no one is actually very interested in this feature and close this issue.
