### ISSUE TITLE
player completes achievement but does not mark as completed or doesn't give rewards

### ISSUE THREAD

**Issue by unholymac** [PyvesB/advanced-achievements#819]
:information_source: **Basic information**

* Advanced Achievements version: 6.2.0
* Minecraft version: 1.15.2
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: 
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: ive tried but not sure how to word it

:beetle: player flew around in a elytra to complete the gliding achievements and they're 1000 blocks over the required block flown in and its still not giving them their reward

:page_facing_up: nothings showed in the console

````

````

:wrench: **Configuration**

````
  '500000':
    Goal: Fly 500000 blocks with an Elytra.
    Message: You traveled 500000 blocks with Elytra!
    Name: distancegliding_500000
    DisplayName: Neverland!
    Reward:
      Command:
        Execute: cc give virtual crazy 1 PLAYER ; upc addPlayerPermission PLAYER deluxetags.tag.Neverland
        Display: 1 &bDiamond Keys&f & &b[&fNeverLand&b] &6Suffix!

````
![unknown](https://user-images.githubusercontent.com/59938744/89846455-35e5cd80-db79-11ea-83e0-d09f232aa03b.png)

**Comment by unholymac** [comment]
i'm not sure what to change since the new update has broken all my rewards which took days to configure

**Comment by PyvesB** [comment]
Hello @unholymac,

If my understanding is correct, this broke when you updated to version 6.2.0? Were you on version 6.1.3 previously?

**Comment by unholymac** [comment]
yes that is correct :D

**Comment by PyvesB** [comment]
Version 6.2.0 of the plugin introduces individual permissions for every achievement, for example `achievement.place_100_stone`. They are set to true by default (see [here](https://github.com/PyvesB/advanced-achievements/blob/d8e58e268324452e02f649f05874aaa946a4c107/advanced-achievements-plugin/src/main/java/com/hm/achievement/lifecycle/PluginLoader.java#L309)) so you shouldn't have to do anything in most cases, but maybe your permissions plugin or setup is overriding those defaults. It's something worth double-checking anyway. 😉

**Comment by unholymac** [comment]
where would i look? i'm not good with code

**Comment by PyvesB** [comment]
Well I wouldn't know: it depends on your permissions plugin and how you've set your server up!

**Comment by unholymac** [comment]
hmmm i use ultra permissions but it was fine before this new update

**Comment by PyvesB** [comment]
There's a plugin version with additional logging available in #831, it may help with debugging permission issues here as well.

**Comment by unholymac** [comment]
New update is having the same issue can you make a permission where every achievement will be counted instead of individual i have 500+ achievements its going to take a very long time doing each individual permission!!

**Comment by PyvesB** [comment]
? There is no new update, version 6.2.0 is the latest.

**Comment by unholymac** [comment]
6.2.0 is the newest update

**Comment by unholymac** [comment]
i just updated to it today and now players are saying their time played achievement is saying 100.6/100

**Comment by unholymac** [comment]
is there a way to give players every count permission instead of doing all 500+ achievements individually?

**Comment by unholymac** [comment]
are you there bro?

**Comment by PyvesB** [comment]
> 6.2.0 is the newest update

Yes, that's exactly what I indicated in my previous message. Unsure why you're stating it again, wouldn't I know anyway given that I publish new versions of the plugin?

On August 11th:
>     * Advanced Achievements version: 6.2.0

On September 9th:
> i just updated to it today

The least I can say is that this is contradictory, but I'm guessing it doesn't matter much - it does create noise and confusion though.

> is there a way to give players every count permission instead of doing all 500+ achievements individually?

Yes, as indicated in https://github.com/PyvesB/advanced-achievements/issues/819#issuecomment-672686822, this is even the intended default behaviour. Every player should be given all the permissions to receive all the achievements, unless you explicitly override the default behaviour in your permissions setup.

As I've stated multiple times already, this is likely an issue with your permissions plugin. After all, you indicated using a niche permissions plugin with few users, so it would be significantly less road-tested than more popular alternatives. Version 6.2.0 of Advanced Achievements was released over a month ago and has already been downloaded several thousand times on dev.bukkit and spigot.org, if the plugin's main functionality, i.e. receiving achievements, no longer worked, there would probably have been hundreds of reports by now.

I've been helpful and linked in https://github.com/PyvesB/advanced-achievements/issues/819#issuecomment-685001393 to an Advanced Achievements version that I took time to build with additional logging, to assist when debugging problems with permissions. You seemed to have ignore that message as well. I'm not omnipotent and can't magically solve bugs in third-party software which I know nothing about and don't even have access to. If you want to see things progress, you have to also start putting in some effort, rather than passive-aggressively asking "are you there?".

**Comment by unholymac** [comment]
Sorry i didn't understand #819 comment or know how to get to pluginManager.addPermission(new Permission(permissionNode, PermissionDefault.TRUE)); and what do you mean by  "maybe your permissions plugin or setup is overriding those defaults."

**Comment by unholymac** [comment]
I'm sorry im not a dev or smart but this makes no sense to me 

"Version 6.2.0 of the plugin introduces individual permissions for every achievement, for example achievement.place_100_stone. They are set to true by default (see here) so you shouldn't have to do anything in most cases, but maybe your permissions plugin or setup is overriding those defaults. It's something worth double-checking anyway. "

**Comment by PyvesB** [comment]
> I'm sorry im not a dev or smart but this makes no sense to me

That's okay, let me try to rephrase things differently. :)

When a plugin developer defines a permission for a given action in their plugin, the permission can have a number of states:
* true => the player can perform the action.
* false => the player cannot perform the action.
* op => the player can only perform the action if they are a server operator.
* not_op => the player can only perform the action if they are not a server operator.

You can define a default state to permissions: basically if you don't change anything, that will become the state of the permission on your server. In Advanced Achievements 6.2.0, achievement permissions are set to true by default: all players should be able to receive achievements a permissions plugin doesn't change the default state, for example from true to false.

This is obviously not the case with your setup. It can be one of:
* a bug in Advanced Achievements. I'm not able to reproduce locally, I've double-checked the code and there only are a couple of reports of this problem. That's why I think it's unlikely.
* something is incorrectly configured on your side.
* a bug in Ultra Permissions. This is the most likely scenario in my opinion.

To progress this, please download the version attached to https://github.com/PyvesB/advanced-achievements/issues/831#issuecomment-684503842. Ask a player to perform an action that should give them an achievement, but doesn't. Collect all logs that contain `[PERMISSIONS]`, including the ones when the plugin starts up. Paste them here and I'll have a look. That will hopefully tell us which of the cases listed above it is.

**Comment by unholymac** [comment]
Start Up- https://pastebin.com/wkxm7GFr

After action - https://pastebin.com/Db9niTHR

**Comment by PyvesB** [comment]
You previously indicated that "time played achievement is saying 100.6/100".

I see the two following related log messages:
> [08:21:22] [Server thread/INFO]: [AdvancedAchievements] [PERMISSIONS] Setting permission achievement.playedtime_100 with  PermissionDefault.TRUE.
> [08:22:55] [Server thread/INFO]: [PERMISSIONS] Checking permission achievement.playedtime_100 for achievement award.

Things seem to line up as expected on the Advanced Achievements side, no obvious bug there. If you think that you've done nothing wrong with your Ultra Permissions setup, I suggest contacting the author. You can include something along the following lines in your message:

> I'm using a plugin that dynamically adds permissions when it starts up using Bukkit's [addPermission](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/plugin/PluginManager.html#addPermission(org.bukkit.permissions.Permission)) API, with permission nodes set to `PermissionDefault.TRUE`. It seems that Ultra Permissions is not handling those correctly.

**Comment by unholymac** [comment]
its all achievements but it works when i give them the individual permission do achievement.itemeaten.25 but to type out over 500+ achievements will take a very long time

**Comment by unholymac** [comment]
they have a option to enable true permission defaults but its broken most of my other permissions please can you add a permission like achievement.catagoryname.*  if you can't i will have to stay on 6.1.3

**Comment by PyvesB** [comment]
> they have a option to enable true permission defaults

Again, it surprises me that Ultra Permissions wholesale overrides all default permissions set by other plugins. This seems like misuse of the permission system to me and renders parts of the Bukkit/Spigot API completely useless. [This class](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/permissions/PermissionDefault.html) and anything using it lose their functionality for example.

> please can you add a permission like achievement.catagoryname.*

The intention is actually to have all permissions depend on the parent `achievement.*`, but I don't think it's the case for the new individual permissions, so that's an oversight and I can change that. You should be able to give `achievement.*` and then set permissions such as `achievement.delete` and other admin commands to false.
