### ISSUE TITLE
When?

### ISSUE THREAD

**Issue by msmanui** [PyvesB/advanced-achievements#835]
Do u think is just pure unluck that 30% of the reviews ask about the same? MORE CUSTOMAZATION. 

1) Why u cant change the achievement in the specific lore  u want?
2) Why u cant each the speicifc display item for each ahivement
3) Why u cant build your own design for each ahivement once is completed, semi-completed or not started
4) Why u cant use all the colors u want like &6 or &7 rather than chosing only 2 for all? 

It would be nice all users can build they own design, not everying likes your design. Thats why 99,99% of the plugins in spigot offers own customazation.

**Comment by fjeddy** [comment]
lol, just.... lol....

**Comment by DXUltimate** [comment]
Nice invalid bug report. lol

**Comment by msmanui** [comment]
So now because i didnt say "hi" my suggestions are invalid.  The author refuses all reviews that complaint about the customaztion. Still i havent seen not a single upgrade of related  to that. 
¿Why?  ¿He belives all the reviews are a conspiracy against him?

**Comment by fjeddy** [comment]
No, they are not invalid, it's not just a bug, it's a feature request.

Secondly, you're literally DEMANDING features, with your shitty English and incompetent point of view. You're harassing the developer for not doing EXACTLY as YOU want, or 30% of those leaving a review. Why don't you just make your own plugin exactly the way YOU want to? Oh wait... You have no clue how.

What I find the funniest tho, is you thinking that your attitude is going to make the developer make what you want. I'm pretty sure you've just made him / her go "Fuck it" and ignore every single request you make.

Lastly, most developers on minecraft make something they need for themselves, something they want to use, made in the way they need it, covering the purposes they use it for. And we are lucky enough to have some of them share their plugins with the public. There are incredible few, if any? plugin developers that make plugins solely to satisfy ignorant pricks like you.

If you don't like what the plugin has to offer, find another plugin, if no other plugin exist, make your own, if, like in your case, you have absolutely no idea how a plugin is made or where to even begin, then by all means ask the developer if he might consider implementing what you need, but do under no circumstances demand, offend or ridicule the developer in the process.

You act like you've paid a fortune for a plugin that has detailed descriptions of what it does when you bought it, and then after your purchase, demand that the creator changes the plugin to suit your exact needs. It doesn't work like that, and to make it even worse, then you're doing it towards a completely free plugin then you haven't paid a cent for.

People like YOU, @msmanui, are one of the biggest reasons plugins halt and die. Simply because your attitude pisses the developers off.

**Comment by msmanui** [comment]
> No, they are not invalid, it's not a bug, it's a feature request, technically a bunch of requests in one go.
> 
> Secondly, you're literally DEMANDING features, with your shitty English and incompetent point of view. You're harassing the developer for not doing EXACTLY as YOU want, or 30% of those leaving a review. Why don't you just make your own plugin exactly the way YOU want to? Oh wait... You have no clue how.
> 
> What I find the funniest tho, is you thinking that your attitude is going to make the developer make what you want. I'm pretty sure you've just made him / her go "Fuck it" and ignore every single request you make.
> 
> Lastly, most developers on minecraft make something they need for themselves, something they want to use, made in the way they need it, covering the purposes they use it for. And we are lucky enough to have some of them share their plugins with the public. There are incredible few, if any? plugin developers that make plugins solely to satisfy ignorant pricks like you.
> 
> If you don't like what the plugin has to offer, find another plugin, if no other plugin exist, make your own, if, like in your case, you have absolutely no idea how a plugin is made or where to even begin, then by all means ask the developer if he might consider implementing what you need, but do under no circumstances demand, offend or ridicule the developer in the process.
> 
> You act like you've paid a fortune for a plugin that has detailed descriptions of what it does when you bought it, and then after your purchase, demand that the creator changes the plugin to suit your exact needs. It doesn't work like that, and to make it even worse, then you're doing it towards a completely free plugin that you haven't paid a cent for.
> 
> People like YOU, @msmanui, are one of the biggest reasons plugins halt and die. Simply because your attitude pisses the developers off.


Dude, stop, okay? I own a large network btwn 500-700 players and  everything i add has to be with a profesional design, therefore, all the plugins i use or used, offer to change the design of the plugin. THIS PLUGIN DOESNT OFFER BASIC STUFF THAT 99,99% WOULD OFFER. U re force to use the gui design of this plugin, which u cant even change the  display item of each achivement or changing the order of the messages. 
A lot of people already complained about this, but the owner seems to ignore every opinion on this. This plugin LACK of customzation gui, simple as that.

**Comment by PyvesB** [comment]
Thanks for weighing in @DXUltimate and @fjeddy.
