### ISSUE TITLE
Command-based achievements add MultiCommand separately.

### ISSUE THREAD

**Issue by king-glitch** [PyvesB/advanced-achievements#863]
:clipboard: **Description**
Command-based achievements add MultiCommand separately.

On Command - based achievements add multi command separately please. 
etc.
```
aachCmd1:
    Goal: 'Foo'
    Message: Bar
    Name: FOO_BAR
    DisplayName: FOO BAR
    MultiCommand: true
    Reward:
        Command:  'say foo bar'
```

**Comment by PyvesB** [comment]
Hello @king-glitch,

Could you please expand on the use-case? Why do you need to make `MultiCommand` a per-achievement parameter?

**Comment by king-glitch** [comment]
I don't really have a reason, but I want to use this plugin for many cases. Like a quest plugin.

**Comment by PyvesB** [comment]
So in the context of your quests setup, do you have a concrete example in mind where some command-based achievements could be obtained only once whilst others could be obtained multiple times?

**Comment by king-glitch** [comment]
Like, when every time player level up, and one time is when player meet the requirement level.

**Comment by PyvesB** [comment]
The _MaxLevel_ achievement category already allows you to fulfil the one time level met requirement, unsure why you would want to do that through the command-based category instead.

**Comment by PyvesB** [comment]
Any news here? I'm being conservative on this one because of the following reasons:
* no one else has ever asked for this in half a decade that command-based achievements have existed.
* it leads to more complex configuration and makes the `Commands` section inconsistent with other achievement categories.
* it will force current users to update their configuration and duplicate the parameter in all their existing achievements.

Unless there are some strong use-cases to justify this, implementing this feature would do more harm than good.

**Comment by king-glitch** [comment]
Oh, Sorry. The level I meant is like not the actual level. It's more like skyblock level. or Prison level. When they prestage I want some of command-cases to work again, but yeah you where right. It leads to more complex configuration and in the sense that it would become inconsistent. I think I don't really have a strong use cases. Sorry for the wrong response.

**Comment by PyvesB** [comment]
It's okay, thanks for coming back to me! For now, I think it's best to close this. However, if any new use case comes to light, feel free to ping me, this issue can be reopened and discussed again at any point. 😉
