### ISSUE TITLE
error connect database

### ISSUE THREAD

**Issue by tccoolFr** [PyvesB/advanced-achievements#900]
Hello, 

Due to a problem with our economy plugin, we removed the plugin to only use most of the economy, except that since we have this advancedachievement no longer connects to the database with this error what to do?

http://pastebin.fr/75084

Suite à un problème avec notre plugin économie, nous avons supprimé le plugin pour ne nous servir que d'essentiel de l'économie, sauf que depuis que nous avons cela advancedachievement ne ce connecte plus à la base de données avec cette erreur que faire?

**Comment by PyvesB** [comment]
Hello @tccoolFr ! 👋🏻 

Out of interest, which economy plugin was it? Did you happen to upgrade the version of Advanced Achievements at the same time?

**Comment by tccoolFr** [comment]
Hello,
It was about CraftConomy3 .3.3.1 except that my server is in 1.16.3 craftconomy is having problems with the jobs

Bonjour,
Il s'agissait de CraftConomy3 .3.3.1 sauf que mon serveur est en 1.16.3 craftconomy pose des problème avec les jobs

**Comment by PyvesB** [comment]
I've just checked, Craftconomy uses a very, very old version of the H2 database, [version 1.4.187](https://github.com/greatman/craftconomy3/blob/51b1b3de7d039e20c7418d1e70b8c4b02b8cf840/build.gradle#L110), which was released all the way back in April 2015. I'm guessing the Craftconomy database drivers took priority over the Advanced Achievements ones, so you ended up with Advanced Achievements running a database in version 1.4.187 instead of latest 1.4.200. By uninstalling Craftconomy, you effectively got rid of the conflict that plugin was causing, but that also meant that the drivers got fast forwarded half a decade in time.

H2 seems to behave poorly on big upgrades such as these, there are a lot of open bug reports with errors similar to yours, for example:
https://github.com/h2database/h2database/issues/2078
https://github.com/h2database/h2database/issues/2590
https://github.com/h2database/h2database/issues/2471
https://github.com/h2database/h2database/issues/2263

The author recommends a migration workaround (https://github.com/h2database/h2database/issues/2078#issuecomment-545409412), you should give it a go.

As a side note, probably best to not go back to Craftconomy, using a plugin that hasn't been updated in years and years will only lead to trouble. 😉

**Comment by PyvesB** [comment]
@tccoolFr any luck with the above suggestions?
