### ISSUE TITLE
Please add support for offline player

### ISSUE THREAD

**Issue by CloudeLecaw** [PyvesB/advanced-achievements#973]
/aach add amount cat player
at the moment its a requiement the player has to be online.

we have a votecounter
  - aach add 1 Custom.votes [playerName]
 this counter only increases at the moment of the player is online..
would be nice if the value alsocould be added if the player is offline.

It happens often that a player votes for the server while he is offline. Currenty he does not get his vote counted that way even if the command is executed correct.. the result is just "the player is not online"

So could you add support for adding amount in a cat to a player? maybe just by  UUID if not possible by playername? :3

player is online:
![image](https://user-images.githubusercontent.com/12080017/110310568-fb56ed00-8002-11eb-8299-801398bcc6d9.png)
all fine...
.
player is offfline
![image](https://user-images.githubusercontent.com/12080017/110310689-1d506f80-8003-11eb-8ca3-abf70385e628.png)
the stats of the player is not increased :-(

**Comment by PyvesB** [comment]
Hello @CloudeLecaw ! :wave:

As you've noted, the _/aach add_ command does not work for offline players. Trying to increase the counter offline would no do what you would expect. By design, checking thresholds and awarding achievements only happens at the point when a given statistic is increased. If the player is offline, the achievement will not be awarded, and player's progress will end up in an inconsistent state, for example progress bars in the GUI showing 13/10 and the achievement still not being received.

I don't know how your vote counter works, but calling _aach add_ only after when the player joined the server would solve the problem. 😉

**Comment by CloudeLecaw** [comment]
Could u tell ne how i give a reward/command only after the player joins? This would need sime kind like a storeage.. that a vote was done.

**Comment by PyvesB** [comment]
Yes, some kind of storage would do the trick. Alternatively, you can increase the statistic in Advanced Achievement's database directly, and then force the statistic synchronisation on player join by running `/aach add 0 Custom.votes PLAYER`.

**Comment by CloudeLecaw** [comment]
how to force the increase of the Adanced Achivments database statisic diectly by command?

**Comment by PyvesB** [comment]
> how to force the increase of the Adanced Achivments database statisic diectly by command?

As indicated previously, you cannot do this via command. You would need to write to the database or integrate with the API to do that.

**Comment by CloudeLecaw** [comment]
The normal user now works with api *outch*
So the answer is its not possible for the normal user. Ok
